language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '8'
before_script:
  - npm prune
after_success:
  - npm run coverage
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
